cls
javac *.java
start /B java -cp . Server
ste /p=
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
java -cp . Client
